Implement #369 feature (reportes in HTTP extension).
LLK/scratch-flash pull request #671
Opened 2015-03-16 02:23 UTC by la10736

Requester don't need to use busy list. Implemented waiting dictionary and block request
state reset on reset_all requests and polling http errors events.

 1. busy information was already in waiting dictionary
 2. On reset_all or connection error (polliing error) is better reset all reporter blocks state

2015-07-21 04:06 UTC, sclements commented
@cwillisf can you take a look at this? we need to make sure this doesn't break Javascript extensions.

2016-09-19 22:32 UTC, cwillisf commented on src/extensions/ExtensionManager.as
> +			}
Shouldn't this still collect `loader.data`?

2016-09-19 22:34 UTC, cwillisf commented on src/extensions/ExtensionManager.as
> -		var index:int = ext.busy.indexOf(id);
I'm nervous about removing the use of `ext.busy` for reporters / requesters. It looks OK at first glance but if possible I'd prefer a more conservative change that only implements HTTP requesters without affecting the way we track requesters in general.

2016-09-19 22:36 UTC, cwillisf commented on src/extensions/ExtensionManager.as
> +				var retval:String = value.slice(i + 1);
It may be possible to simplify this by using `value.split` as in the `'_busy'` case.

2016-09-19 22:39 UTC, cwillisf requested changes
Sorry this took so long to get to. We're postponing many improvements until Scratch 3.0, but I think this one might make sense to integrate into 2.0 for those still using HTTP extensions.

2016-09-20 07:32 UTC, la10736 commented
I'll try to take a look to it in the next days... after 1.5 years without working to it is hard to recover all details.

2017-09-03 22:53 UTC, thisandagain commented
Thanks for the contribution!

Scratch 2.0 is now in maintenance mode while the team focuses efforts on [Scratch 3.0](https://llk.github.io/scratch-gui). While critical issues will be addressed please note that any feature requests or minor issues will not be reviewed until 3.0 is released. Because of this, we will be closing this PR and only accepting patches to `scratch-flash` that resolve bugs labeled as `prio-critical`. 

If you are interested in contributing to Scratch 3.0 please take a look at the following repositories:
https://github.com/llk/scratch-gui
https://github.com/llk/scratch-blocks
https://github.com/llk/scratch-vm
https://github.com/llk/scratch-render
https://github.com/llk/scratch-audio

2017-09-03 22:53 UTC, closed without merging